### ISSUE TITLE
fix is_ffmpeg_compatible() method

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/control-panel#2]
```
def is_ffmpeg_compatible(file_url) -> bool:
    """
    Checks to see if the file (local and non-local) is compatible with ffmpeg.
    :returns: success
    """
    # command = f"{FFMPEG} -y -v error -i {file_url} {os.path.join(WIN_TMP, 'verify-ffmpeg.png')}"
    # err = subprocess.run(command.split(" "), capture_output=True).stderr
    # return err == b''

    # ABOVE BROKEN DOESN"T WORK
    return True
```

**Comment by tylerecouture** [comment]
This is critical to preventing images from breaking the video creation: e.g.
![image](https://github.com/timberline-secondary/control-panel/assets/10604391/2e83368e-0399-4fdb-a353-f13a25398590)

**Comment by tylerecouture** [comment]
Here's an example image that was breaking it:
https://d10ge8y4vx8iud.cloudfront.net/public_media/portfolios/video/2023/12/IMG_0604.png

**Comment by tylerecouture** [comment]
Did we used to re-save all images locally using PIL to remove all these issues?
![image](https://github.com/timberline-secondary/control-panel/assets/10604391/3b4899fc-9623-4355-b3ed-45132688deca)

**Comment by tylerecouture** [comment]
@punctuations This is still an issue.  Some basic PNGs are breaking ffmpeg, why isn't this caught by `is_ffmpeg_compatible` whent he images are uploaded?  Here's the link to the image: 
https://d10ge8y4vx8iud.cloudfront.net/public_media/portfolios/video/2024/01/zombie_moth.png

Here's the error:

![image](https://github.com/timberline-secondary/control-panel/assets/10604391/4ed6ade5-9c5f-41fd-905c-7979e794196e)

**Comment by tylerecouture** [comment]
@punctuations broken code is currently commented out, but if I run it directly (with code not commented out) here's the error:

![image](https://github.com/timberline-secondary/control-panel/assets/10604391/c62b1f29-3583-4a5f-a59c-d1200a31ffe4)

**Comment by tylerecouture** [comment]
@punctuations broken code is currently commented out, but if I run it directly (with code not commented out) here's the error:

![image](https://github.com/timberline-secondary/control-panel/assets/10604391/c62b1f29-3583-4a5f-a59c-d1200a31ffe4)

Doesn't work with local file either:
![image](https://github.com/timberline-secondary/control-panel/assets/10604391/a4d0e746-2da0-4a26-aa6c-df2737a49fc1)

**Comment by punctuations** [comment]
@tylerecouture Could this be an issue with the FFMPEG variable path? Did it change or did something update?

**Comment by tylerecouture** [comment]
Does it work for you?  It's not clear from the error WHAT file it can't find.

**Comment by tylerecouture** [comment]
@punctuations path to FFMPEG is correct:

verifying the path from python shell:
![image](https://github.com/timberline-secondary/control-panel/assets/10604391/b038ce29-b6d9-4092-80fc-855343e672b8)

Running it in cmd:
![image](https://github.com/timberline-secondary/control-panel/assets/10604391/31ea7797-a180-4362-8437-5e82d336fd0a)

**Comment by tylerecouture** [comment]
BOOM!  Thank you!

![image](https://github.com/timberline-secondary/control-panel/assets/10604391/fe92a811-8849-4d1d-b585-f92fd5a160eb)

Now how to deal with pngs that aren't compatible.,... haha.  If I download and re-save the image with GIMP it works, so I think we could just try to resave it using PIL?

**Comment by tylerecouture** [comment]
Doesn't work for urls:

@punctuations this returns false for any url.  When I print `err`:

![image](https://github.com/timberline-secondary/control-panel/assets/10604391/9e08d735-1e5b-466e-a8df-2b491db787a8)

**Comment by punctuations** [comment]
Looks like an issue to do with ffmpeg version then, is the ffmpeg via krita the end all be all for ffmpeg or could the version be updated to allow for direct "ffmpeg" calling the cli and url support?

**Comment by tylerecouture** [comment]
We could just download a standalone version ourselves for the control panel.

**Comment by punctuations** [comment]
Alrighty

**Comment by tylerecouture** [comment]
All that function does is return true, you didn't uncomment out the method's code, haha....

**Comment by tylerecouture** [comment]
@punctuations your branch was not up to date and did not include the reversion.  Make sure you git pull and merge, and deal with any issues before you push
